sonar.projectKey=jarvis-os
sonar.organization=statick88
sonar.sources=jarvis_os
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**,**/migrations/**,**/alembic/**,**/__pycache__/**,**/__init__.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.login=squ_583d17a1ddcbd7c55bb84514400cd09a8afb1031
